
[server]
headless = true
address = "0.0.0.0"
port = 5000
enableXsrfProtection = false

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"
base = "light"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false

[markdown]
codeCopyButton = true

[deprecation]
showPyplotGlobalUse = false
